import axios from 'axios';
import React, { Component } from 'react';
import MyContext from '../contexts/MyContext';
import vi from '../lang/vi';

class CategoryDetail extends Component {
  static contextType = MyContext;
  constructor(props) {
    super(props);
    this.state = {
      txtID: '',
      txtName: '',
      txtImageFile: null,
      txtImageUrl: '',
      errors: {},
      isSubmitting: false
    };
  }

  componentDidMount() {
    this.resetForm();
  }

  componentDidUpdate(prevProps) {
    if (this.props.item !== prevProps.item) {
      if (this.props.item) {
        this.setState({
          txtID: this.props.item._id,
          txtName: this.props.item.name,
          txtImageUrl: this.props.item.image || '',
          txtImageFile: null,
          errors: {}
        });
      } else {
        this.resetForm();
      }
    }
  }

  resetForm = () => {
    this.setState({
      txtID: '',
      txtName: '',
      txtImageFile: null,
      txtImageUrl: '',
      errors: {}
    });
  }

  validateForm = () => {
    const errors = {};
    
    // Validate category name
    if (!this.state.txtName || this.state.txtName.trim() === '') {
      errors.txtName = vi.categoryNameRequired;
    } else if (this.state.txtName.trim().length < 2) {
      errors.txtName = vi.categoryNameMinLength;
    } else if (this.state.txtName.trim().length > 50) {
      errors.txtName = vi.categoryNameMaxLength;
    }

    if (!this.props.item && !this.state.txtImageFile) {
      errors.txtImageFile = 'Hình ảnh danh mục là bắt buộc.';
    }

    return errors;
  }

  handleFieldChange = (fieldName, value) => {
    this.setState(prev => ({
      [fieldName]: value,
      errors: {
        ...prev.errors,
        [fieldName]: ''
      }
    }));
  }

  handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      this.setState({
        txtImageFile: file,
        txtImageUrl: URL.createObjectURL(file),
        errors: { ...this.state.errors, txtImageFile: '' }
      });
    }
  }

  render() {
    return (
      <div className="category-detail-modal">
        <div className="modal-backdrop" onClick={this.props.onClose}></div>
        <div className="modal-content">
          <div className="modal-header">
            <h3>{this.props.item ? vi.editCategory : vi.addNewCategory}</h3>
            <button 
              className="close-btn" 
              onClick={this.props.onClose}
              disabled={this.state.isSubmitting}
            >
              <i className="icon-close"></i>
            </button>
          </div>

          <div className="modal-body">
            <form className="category-form">
              {/* ID Field - Read Only */}
              <div className="form-group">
                <label className="form-label">
                  {vi.categoryId}
                  <span className="field-hint"> {vi.autoGenerated}</span>
                </label>
                <input
                  type="text"
                  value={this.state.txtID}
                  readOnly={true}
                  className="form-input readonly"
                  disabled
                />
              </div>

              {/* Category Name Field */}
              <div className="form-group">
                <label className="form-label">
                  {vi.categoryName}
                  <span className="required">{vi.required}</span>
                  <span className="field-hint"> {vi.charactersRange}</span>
                </label>
                <input
                  type="text"
                  value={this.state.txtName}
                  onChange={(e) => this.handleFieldChange('txtName', e.target.value)}
                  className={`form-input ${this.state.errors.txtName ? 'input-error' : ''}`}
                  placeholder={vi.enterCategoryName}
                  maxLength="50"
                  disabled={this.state.isSubmitting}
                />
                <span className="field-counter">
                  {this.state.txtName.length}/50
                </span>
                {this.state.errors.txtName && (
                  <span className="error-message">{this.state.errors.txtName}</span>
                )}
              </div>

              {/* Category Image Field */}
              <div className="form-group">
                <label className="form-label">
                  Hình ảnh danh mục
                  <span className="required">{vi.required}</span>
                </label>
                {this.state.txtImageUrl && (
                  <div className="image-preview">
                    <img src={this.state.txtImageUrl} alt="Danh mục" className="preview-image" />
                  </div>
                )}
                <input
                  type="file"
                  accept="image/*"
                  className={`form-input ${this.state.errors.txtImageFile ? 'input-error' : ''}`}
                  onChange={(e) => this.handleImageChange(e)}
                  disabled={this.state.isSubmitting}
                />
                {this.state.errors.txtImageFile && (
                  <span className="error-message">{this.state.errors.txtImageFile}</span>
                )}
              </div>
            </form>
          </div>

          <div className="modal-footer">
            <button
              type="button"
              className="btn btn-secondary"
              onClick={this.props.onClose}
              disabled={this.state.isSubmitting}
            >
              {vi.cancel}
            </button>

            {this.props.item ? (
              <>
                <button
                  type="button"
                  className="btn btn-danger"
                  onClick={(e) => this.btnDeleteClick(e)}
                  disabled={this.state.isSubmitting}
                >
                  {this.state.isSubmitting ? vi.deleting : vi.delete}
                </button>
                <button
                  type="button"
                  className="btn btn-primary"
                  onClick={(e) => this.btnUpdateClick(e)}
                  disabled={this.state.isSubmitting}
                >
                  {this.state.isSubmitting ? vi.updating : vi.updateCategory}
                </button>
              </>
            ) : (
              <button
                type="button"
                className="btn btn-primary"
                onClick={(e) => this.btnAddClick(e)}
                disabled={this.state.isSubmitting}
              >
                {this.state.isSubmitting ? vi.adding : vi.addCategory}
              </button>
            )}
          </div>
        </div>
      </div>
    );
  }

  // Event handlers
  btnAddClick(e) {
    e.preventDefault();
    const errors = this.validateForm();

    if (Object.keys(errors).length > 0) {
      this.setState({ errors });
      return;
    }

    this.setState({ isSubmitting: true });
    const formData = new FormData();
    formData.append('name', this.state.txtName.trim());
    if (this.state.txtImageFile) {
      formData.append('image', this.state.txtImageFile);
    }
    this.apiPostCategory(formData);
  }

  btnUpdateClick(e) {
    e.preventDefault();
    const errors = this.validateForm();

    if (Object.keys(errors).length > 0) {
      this.setState({ errors });
      return;
    }

    const id = this.state.txtID;
    this.setState({ isSubmitting: true });
    const formData = new FormData();
    formData.append('name', this.state.txtName.trim());
    if (this.state.txtImageFile) {
      formData.append('image', this.state.txtImageFile);
    }
    this.apiPutCategory(id, formData);
  }

  btnDeleteClick(e) {
    e.preventDefault();
    if (window.confirm(vi.confirmDeleteCategory)) {
      const id = this.state.txtID;
      this.setState({ isSubmitting: true });
      this.apiDeleteCategory(id);
    }
  }

  // APIs
  apiPostCategory(cate) {
    const config = { headers: { 'x-access-token': this.context.token, 'Content-Type': 'multipart/form-data' } };
    axios.post('/api/category/admin/add', cate, config).then((res) => {
      const result = res.data;
      if (result) {
        alert(vi.categoryAddedSuccessfully);
        this.setState({ isSubmitting: false });
        this.props.onClose();
        this.props.updateCategories();
      } else {
        alert(vi.failedToAddCategory);
        this.setState({ isSubmitting: false });
      }
    }).catch((error) => {
      alert(vi.errorAddingCategory);
      this.setState({ isSubmitting: false });
      console.error(error);
    });
  }

  apiPutCategory(id, cate) {
    const config = { headers: { 'x-access-token': this.context.token, 'Content-Type': 'multipart/form-data' } };
    axios.put('/api/category/admin/update/' + id, cate, config).then((res) => {
      const result = res.data;
      if (result) {
        alert(vi.categoryUpdatedSuccessfully);
        this.setState({ isSubmitting: false });
        this.props.onClose();
        this.props.updateCategories();
      } else {
        alert(vi.failedToUpdateCategory);
        this.setState({ isSubmitting: false });
      }
    }).catch((error) => {
      alert(vi.errorUpdatingCategory);
      this.setState({ isSubmitting: false });
      console.error(error);
    });
  }

  apiDeleteCategory(id) {
    const config = { headers: { 'x-access-token': this.context.token } };
    axios.delete('/api/category/admin/delete/' + id, config).then((res) => {
      const result = res.data;
      if (result) {
        alert(vi.categoryDeletedSuccessfully);
        this.setState({ isSubmitting: false });
        this.props.onClose();
        this.props.updateCategories();
      } else {
        alert(vi.failedToDeleteCategory);
        this.setState({ isSubmitting: false });
      }
    }).catch((error) => {
      alert(vi.errorDeletingCategory);
      this.setState({ isSubmitting: false });
      console.error(error);
    });
  }
}

export default CategoryDetail;